### ISSUE TITLE
make gates consistant for steps 1-6

### ISSUE THREAD

**Issue by dadamsncsa** [nanoMFG/python-best-practices-v2#108]
## Description
* The check for file gates for steps 1-6 should be consistent and...:
  - Have working file edit links.
  - Not break the step

Note the original check code I pasted for these assumes that it was checking for a file in the wrong location.  I don;t think we need to do that, just check if the file exists in the right location and if it doesn't, prompt the user to create it

**Comment by adamurish** [comment]
I standardized the format of all the file checking gates. There are still issues with the edit links, but the general structure of the gates is working as intended.
